### ISSUE TITLE
请问那个版本支持摇杆？

### ISSUE THREAD

**Issue by Richard1ybb** [blinker-iot/blinker-app#1]
`请问那个版本支持摇杆？`

`如果把这些注释去掉，我自己重新编译是否可用支持摇杆？
`![image](https://user-images.githubusercontent.com/28901625/79317577-6e153080-7f38-11ea-8bac-1f3a0567f0bb.png)

**Comment by coloz** [comment]
最新版面向专业版用户已经开放摇杆，自己修改源码重新编译，也可以开启摇杆。
